### ISSUE TITLE
BigFileV3 seems to be missing from the source

### ISSUE THREAD

**Issue by LennardF1989** [gibbed/Gibbed.Disrupt#1]
Good to see activity on the Watch Dogs Legion side of things, thanks! Was looking into maybe assisting in some regard. Currently, your source is missing the BigFileV3 class. I can generate it based on all the usages right now, but I thought I should let you know at the very least :)

**Comment by LennardF1989** [comment]
Looks like the rename you did a few commits back only removed the file, but never added the BigFileV3 back.

**Comment by gibbed** [comment]
Not sure how that happened, thought I added it when I did the rename. There's a bunch of pending code pushes for WDL once the code is ready.

**Comment by gibbed** [comment]
Should be resolved as of 3e3d1f6.
