### ISSUE TITLE
Is Namespace 'Gibbed.ProjectData' Missing Type or Namespace Name 'Manager'?

### ISSUE THREAD

**Issue by skycat2216** [gibbed/Gibbed.Disrupt#10]
I'm trying to build Gibbed.Disrupt, and i have some problem.
```
C:\Users\[REDACTED]\files\Gibbed.Disrupt\projects\Gibbed.Disrupt.FileFormats\ProjectHelpers.cs(35,30): error CS0234: 命名空間 'Gibbed.ProjectData' 中沒有類型或命名空間名稱 'Manager' (是否遺漏了組件參
考?) [C:\Users\[REDACTED]\files\Gibbed.Disrupt\projects\Gibbed.Disrupt.FileFormats\Gibbed.Disrupt.FileFormats.csproj]
    8 個警告
    1 個錯誤
```

**Comment by gibbed** [comment]
How are you cloning the repository? The repository has submodules that need to be initialized/cloned as well.

ie

`git clone --recurse-submodules https://github.com/gibbed/Gibbed.Disrupt.git`

if you've already cloned the repository you can do

`git submodule init`
`git submodule update`

**Comment by skycat2216** [comment]
Thanks for helping
Now I have a new issue:Is .net Framework 4.6 or higher can be used to retarget?
I'm stuck on MSB3644 now,and net40/45 installation isn't able to proceed

**Comment by gibbed** [comment]
There shouldn't be any issues retargetting to a newer framework version.

**Comment by skycat2216** [comment]
Huge thanks
In the end it just a dependency issue, Just need to type these CLI command to XCompress/Ndesk/Gibbed.IO/Gibbed.ProjectData
`
dotnet add package Microsoft.NETFramework.ReferenceAssemblies.net40 --version 1.0.3
`
`
dotnet add package Microsoft.NETFramework.ReferenceAssemblies.net45 --version 1.0.3
`
Thank you
